# permissions for end users to view roles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: role-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: database-operator
    app.kubernetes.io/part-of: database-operator
    app.kubernetes.io/managed-by: kustomize
  name: role-viewer-role
rules:
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.facets.cloud
  resources:
  - roles/status
  verbs:
  - get
