apiVersion: postgres.facets.cloud/v1alpha1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: role-sample
    app.kubernetes.io/part-of: database-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: database-operator
  name: role-sample
spec:
  # TODO(user): Add fields here
